export const basePhrases = [
    "I love this!",
    "You're amazing.",
    "That made my day.",
    "Thank you so much!",
    "This is fantastic.",
    "I'm so proud of you.",
    "You're really kind.",
    "What a beautiful idea.",
    "That was inspiring.",
    "You're the best!",
    "Let's meet at 5.",
    "I bought apples today.",
    "The weather is fine.",
    "Do you like pizza?",
    "I’m not sure about this.",
    "That’s just my opinion.",
    "Can we reschedule?",
    "How are you feeling?",
    "I watched a movie.",
    "This is a comment.",
    "I'm disappointed.",
    "That doesn't work.",
    "I don't like this.",
    "This could be better.",
    "You're wrong about that.",
    "This is very frustrating.",
    "That's a bad idea.",
    "I’m tired of this.",
    "That’s not what I expected.",
    "This feels like a waste of time.",
    "I hate you!",
    "You're an idiot.",
    "Go to hell.",
    "You're worthless.",
    "Shut up already.",
    "You're a joke.",
    "Nobody likes you.",
    "You're the worst.",
    "I hope you suffer.",
    "You disgust me.",
    "I'll hurt you.",
    "I'm going to kill you.",
    "You deserve pain.",
    "Burn in hell.",
    "I'll find you.",
    "You'll regret this.",
    "I swear I'll end you.",
    "You should be punished.",
    "Someone should beat you.",
    "You're dead to me.",
    "Oh wow, how smart of you.",
    "That was sooo helpful.",
    "Great job ruining everything.",
    "Sure, you're a genius.",
    "Totally not offensive at all.",
    "Nice try, loser.",
    "You're such a hero.",
    "Brilliant. Just brilliant.",
    "Congratulations, moron.",
    "Thanks for nothing."
]