export const basePhrases = [
    "I love this!",
    "You`re amazing.",
    "That made my day.",
    "Thank you so much!",
    "This is fantastic.",
    "I`m so proud of you.",
    "You`re really kind.",
    "What a beautiful idea.",
    "That was inspiring.",
    "You`re the best!",
    "Let`s meet at 5.",
    "I bought apples today.",
    "The weather is fine.",
    "Do you like pizza?",
    "I’m not sure about this.",
    "That’s just my opinion.",
    "Can we reschedule?",
    "How are you feeling?",
    "I watched a movie.",
    "This is a comment.",
    "I`m disappointed.",
    "That doesn`t work.",
    "I don`t like this.",
    "This could be better.",
    "You`re wrong about that.",
    "This is very frustrating.",
    "That`s a bad idea.",
    "I’m tired of this.",
    "That’s not what I expected.",
    "This feels like a waste of time.",
    "I hate you!",
    "You`re an idiot.",
    "Go to hell.",
    "You`re worthless.",
    "Shut up already.",
    "You`re a joke.",
    "Nobody likes you.",
    "You`re the worst.",
    "I hope you suffer.",
    "You disgust me.",
    "I`ll hurt you.",
    "I`m going to kill you.",
    "You deserve pain.",
    "Burn in hell.",
    "I`ll find you.",
    "You`ll regret this.",
    "I swear I`ll end you.",
    "You should be punished.",
    "Someone should beat you.",
    "You`re dead to me.",
    "Oh wow, how smart of you.",
    "That was sooo helpful.",
    "Great job ruining everything.",
    "Sure, you`re a genius.",
    "Totally not offensive at all.",
    "Nice try, loser.",
    "You`re such a hero.",
    "Brilliant. Just brilliant.",
    "Congratulations, moron.",
    "Thanks for nothing.",
    "I love this product!",
    "You`re absolutely worthless.",
    "Thanks for the quick reply.",
    "Why are you like this?",
    "You made my day.",
    "This is so stupid.",
    "Please stop messaging me.",
    "What a brilliant idea!",
    "You should be ashamed.",
    "Can we talk tomorrow?",
    "Nobody wants you here.",
    "This app is amazing!",
    "You don’t know what you’re doing.",
    "I’m really proud of you.",
    "You’re such a disappointment.",
    "Let’s reschedule our meeting.",
    "You’re a genius.",
    "Go away.",
    "You’ve helped me a lot.",
    "Shut your mouth.",
    "I appreciate your honesty.",
    "You`re a complete failure.",
    "Thanks for nothing.",
    "Looking forward to seeing you.",
    "You’ll regret this.",
    "Everything is working well.",
    "You are pathetic.",
    "See you next week!",
    "That’s not how this works.",
    "Thank you so much!",
    "You should be fired.",
    "What a nice surprise!",
    "I hope you fail.",
    "That’s helpful.",
    "You`re disgusting.",
    "I totally agree with you.",
    "You ruin everything.",
    "Well done!",
    "You don’t belong here.",
    "Happy to help!",
    "Why are you even talking?",
    "I like your energy.",
    "You`re such a loser.",
    "Let me know if you need anything.",
    "You should disappear.",
    "I’m so glad we talked.",
    "You’re not even trying.",
    "That really means a lot.",
    "What’s wrong with you?",
    "You’ve been so kind.",
    "You’re just annoying.",
    "Everything looks great!",
    "You’re not important.",
    "Thanks again!",
    "No one asked you.",
    "It’s been a pleasure.",
    "You’re making things worse.",
    "I’m grateful for your help.",
    "That’s the dumbest thing ever.",
    "This is exactly what I needed.",
    "You messed everything up.",
    "Great work!",
    "You never do anything right.",
    "Thanks, I appreciate it.",
    "You`re so dramatic.",
    "This is a solid improvement.",
    "You`re always complaining.",
    "You did a great job.",
    "Just shut up already.",
    "Really impressive work!",
    "Why are you still here?",
    "You’ve gone above and beyond.",
    "Nobody cares.",
    "You’re such a good friend.",
    "I can’t believe how useless you are.",
    "Let’s catch up later.",
    "You`re terrible at this.",
    "You’re the kindest person I know.",
    "No one likes you.",
    "I`m excited about this!",
    "You always ruin the mood.",
    "Thanks for sharing.",
    "You’re nothing special.",
    "I`m very satisfied with the result.",
    "You`re the worst.",
    "This has been really helpful.",
    "Don’t talk to me again.",
    "I had a great experience.",
    "You’re the problem.",
    "Well explained!",
    "Just leave me alone.",
    "That cleared things up.",
    "You always lie.",
    "I’m looking forward to this.",
    "You make everyone uncomfortable.",
    "Very professional, thank you.",
    "Get out.",
    "I appreciate the quick turnaround.",
    "You ruin every conversation.",
    "Let’s connect again soon.",
    "You`re not smart enough.",
    "Thanks, this saved me a lot of time.",
    "You’re a joke.",
    "That’s perfect, thank you."
]